<?php

namespace common\models;

use common\components\Utils;
use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "product".
 *
 * @property integer $id
 * @property string $title
 * @property integer $is_active
 * @property integer $main_category
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $created_at
 * @property string $updated_at
 *
 *
 *  @property Category $mainCategory
 *
 */
class Product extends \yii\db\ActiveRecord
{
    const IS_ACTIVE = 1;
    const IN_ACTIVE = 0;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    public function beforeSave($insert)
    {
        $now = Utils::getNow();
        if($this->isNewRecord){
            $this->created_at = $now;
        }
        $this->updated_at = $now;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'is_active', 'main_category', 'created_by', 'updated_by', 'created_at', 'updated_at'], 'required'],
            [['is_active', 'main_category', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['title'], 'string', 'max' => 255],
            [['main_category'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['main_category' => 'id']],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ]
        ];

    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'is_active' => 'Is Active',
            'main_category' => 'Main Category',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMainCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'main_category']);
    }
}
