<?php

namespace common\models;

use common\components\Utils;
use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "product_category_mapping".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $cat_id
 * @property integer $is_active
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Product $product
 * @property Category $cat
 */
class ProductCategoryMapping extends \yii\db\ActiveRecord
{
    const IS_ACTIVE = 1;
    const IN_ACTIVE = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_category_mapping';
    }

    public function beforeSave($insert)
    {
        $now = Utils::getNow();
        if($this->isNewRecord){
            $this->created_at = $now;
        }
        $this->updated_at = $now;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'cat_id', 'is_active', 'created_by', 'updated_by', 'created_at', 'updated_at'], 'required'],
            [['product_id', 'cat_id', 'is_active', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['product_id', 'cat_id'], 'unique', 'targetAttribute' => ['product_id', 'cat_id'], 'message' => 'The combination of Product ID and Cat ID has already been taken.'],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => Product::className(), 'targetAttribute' => ['product_id' => 'id']],
            [['cat_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['cat_id' => 'id']],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ]
        ];

    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'cat_id' => 'Cat ID',
            'is_active' => 'Is Active',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCat()
    {
        return $this->hasOne(Category::className(), ['id' => 'cat_id']);
    }
}
